### ISSUE TITLE
No file named "polymer_smiles.csv.gz" found in the folder "database"

### ISSUE THREAD

**Issue by ChangwenXu98** [KanHatakeyama/ion_predictor#1]
When launching the jupyter notebook for the regression model and pretraining descriptor data from SMILES data, the file path "database/polymer_smiles.csv.gz" in the file "settings.yaml" does not exist. I think it might be "database/compounds.csv" instead.

**Comment by KanHatakeyama** [comment]
Thanks for your comment.
I noticed that the file "database/polymer_smiles.csv.gz" was not uploaded because of the wrong setting of .gitignore.
Now, it's available in the "database" folder!

**Comment by ChangwenXu98** [comment]
Thank you!
